[project]
name = 'Decentralized-Specialized-Disaster-Response-Equipment'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.deployment-tracking]
path = 'contracts/deployment-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.equipment-registration]
path = 'contracts/equipment-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-scheduling]
path = 'contracts/maintenance-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-verification]
path = 'contracts/training-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
